config/routes.rb
Rails.application.routes.draw do
  root 'index#welcome'
  resources :posts

  get 'gmod/show' => 'gmod#show'

  get 'uploader/' => 'uploader#get'
  post 'uploader/' => 'uploader#upload'

  #auth routing
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/gmod/' => 'gmod#show'
end

app/views/shared/_header.html.erb
<div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
            data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
</div>
<div class="collapse navbar-collapse navbar-inverse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
        <li>
            <a href="/"><i class="fa fa-home"></i>Home</a>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
               aria-expanded="false"><i class="fa fa-group"></i> My Friends<span
            class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
                <li><a href="//notoriousdev.com"><i class="fa fa-code"></i> NotoriousDev</a></li>
                <li><a href="//aero-tech.me"><i class="fa fa-paper-plane"></i> Aero-Tech</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                <i class="fa fa-folder-open"></i>My Stuff
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
                <li>
                    <a href="//github.com/zack6849" target="_blank"><i class="fa fa-github"></i>GitHub</a></li>
                <li>
                    <a href="//bitbucket.com/zack6849" target="_blank"><i class="fa fa-bitbucket"></i>BitBucket</a>
                </li>
                <li>
                    <a href="//github.com/zack6849/SuperLogger/wiki" target="_blank"><i class="fa fa-book"></i>SuperLogger</a>
                </li>
                <li>
                    <a href="//github.com/zack6849/AlphabotV2/" target="_blank"><i class="fa fa-gears"></i>Alphabot</a>
                </li>
                <li>
                    <a href="/gmod/" target="_blank"><i class="fa fa-steam"></i> Garry's mod</a>
                </li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
               aria-expanded="false"><i class="fa fa-send"></i>Contact Me<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
                <li>
                    <a href="skype:zack6949?chat" target="_blank"><i class="fa fa-skype"></i>Skype</a>
                </li>
                <li>
                    <a href="mailto:contact@zack6849.com" target="_blank"><i class="fa fa-envelope"></i>E-Mail</a>
                </li>
                <li>
                    <a href="//webchat.esper.net?channels=zack6849" target="_blank"><i class="fa fa-comments"></i>IRC</a>
                </li>
            </ul>
        </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
            <li class="dropdown" id="user-tools">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                    <i class="fa fa-user"></i><%= current_user.name %> <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li>
                        <a href="<%= new_post_path %>"><i class="fa fa-edit"></i>New Post</a>
                    </li>
                    <li>
                        <a href="/logout"><i class="fa fa-user-times"></i>Sign Out</a>
                    </li>
                </ul>
            </li>
        <% else %>
            <li>
                <a href="/login"><i class="fa fa-lock"></i>Login</a>
            </li>
        <% end %>
        <li>
            <a target="_blank" href="https://www.paypal.com/cgi-bin/webscr?return=https://www.zack6849.com/&cn=Add+special+instructions+to+the+addon+author(s)&business=zcraig29@yahoo.com&bn=PP-DonationsBF:btn_donateCC_LG.gif:NonHosted&cancel_return=https://www.zack6849.com/&lc=US&item_name=Donation%20(from%20www.zack6849.com)&cmd=_donations&rm=1&no_shipping=1&currency_code=USD">
                <i class="fa fa-heart" style="color: red !important;"></i>Donate
            </a>
        </li>
    </ul>
</div>

app/views/shared/_post.html.erb
<div class="post">
    <%
       if @post
         post = @post
       end
    %>
    <h2 class="post-title"><a href="<%= post_path(post) %>"><%= post.title %></a></h2>
    <hr>
    <%= raw post.markdown %>
    <div class="text-right post-info" style="">
        <% if current_user %>
            <a class="tool" href="<%= edit_post_url(post) %>"><i class="fa fa-pencil"></i> Edit</a>
            <a class="tool" data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="<%= post_path(post) %>"><i class="fa fa-trash"></i>
                Delete</a>
        <% end %>
        <small class="post-date">
            <code>Posted: <%= post.created_at.getlocal.strftime(Settings.post.date_format) %></code>
        </small>
    </div>
</div>